# fly.toml app configuration file generated for desenho-online on 2026-04-17T23:12:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'desenho-online'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 8080
  protocol = "tcp"

[[services.ports]]
    port = 80

[[services.ports]]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
